config/routes.rb
Team::Application.routes.draw do
  devise_for :users
  resources :users, :except => [:index,:new,:create]
  resources :groups
  resources :groupships
  resources :homes
  root :to => 'homes#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
         can :manage, :all
    else
         can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
	resourcify
	attr_accessible :name, :user_id, :description,:start,:destination,:limitition,:remark,:link

	has_many :groupships
	has_many :users, through: :groupships

	validates :name,:description, :presence => true
	def self.Pro_select
		province = Hash[ shanghai: "shanghai", xizang: "xizang",
			beijing:  "beijing" ]      
		end
	end

app/models/groupship.rb
class Groupship < ActiveRecord::Base
  attr_accessible :group_id, :user_id

  belongs_to :user
  belongs_to :group
  
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :name,:email, :password, :password_confirmation, :remember_me,
  								:avatar, :avatar_cache, :qq, :gender
  
  has_many :groupships
  has_many :groups, through: :groupships
  
  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!,  :except => [:index,:show]
  respond_to  :html, :xml, :js
  def index
    @q = Group.search(params[:q])
    @groups = @q.result(:distinct => true)
    respond_with @groups
  end

  def show
    @group = Group.find(params[:id])
    respond_with @group
  end

  def new
    @group = Group.new
    respond_with  @group
  end

  def create
    @group = current_user.groups.create(params[:group])
    if @group.save
      current_user.add_role :moderator , @group  
      redirect_to group_path(@group)
    else
      render :action => 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
    respond_with @group
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(params[:group])
      redirect_to @group
    else
      render :action => 'edit'
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_url
  end
end

app/controllers/groupships_controller.rb
# encoding: utf-8
class GroupshipsController < ApplicationController
	
	def create
		@groupship = current_user.groupships.build(:group_id => params[:group_id])
		@is_in_group = is_in_group?(params[:group_id])
		if @is_in_group
			flash[:notice] = "已经在团队中了！"
			redirect_to group_path(params[:group_id])
		elsif @groupship.save
			flash[:notice] = "成功加入团队"
			redirect_to group_path(params[:group_id])
		else
			flash[:notice] = "加入团队失败"
			redirect_to group_path(params[:group_id])
		end
	end

	def destroy
		@groupship = current_user.groupships.find(params[:id])     
		@groupship.destroy 
		flash[:notice] = "退出团队"      
		redirect_to current_user
	end

	private
	def is_in_group?(group_id)
		current_user.groupships.each do |g|
			return true if group_id == g.group_id
		end
		return false
	end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def index
  	@first_image_url = 'home/0.jpg'
  	@image_urls = ['home/1.jpg', 'home/2.jpg']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  respond_to  :html,:json
  
  def show
    @user = User.find(params[:id])
    respond_with @user
  end
  def edit
    @user = User.find(params[:id])
    respond_with   @user
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    respond_with @user 
    #redirect_to @user, :notice  => "Successfully updated user."
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url, :notice => "Successfully destroyed user."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/groupships_helper.rb
module GroupshipsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
 <%= simple_form_for @group,:validate => true do |f| %>
 <div class="modal-body">
   <%= f.input  :name , :placeholder => "团队名称" %> 
   <%= f.select :start , Group.Pro_select.each{|key,value| [key,value]} %>
   <%= f.select :destination,Group.Pro_select.each{|key,value| [key,value]} %>
   <%= f.input :limitition , :placeholder => "人数上限"%>
   <%= f.input  :description , :placeholder => "旅行主题", :input_html => { :rows => 2 } %> 
   <%= f.input  :remark ,:placeholder => "备注", :input_html => { :rows => 2 } %> 
   <%= f.input  :link ,:placeholder => "活动主页" %>   
 </div>
 <div class="modal-footer">
   <%= f.submit "创建团队", :class => "btn btn-primary" %>
 </div>
 <% end %>

app/views/groups/_team_members.html.erb
<ul id="team_member">
  <li>团队成员：</li>
  <% for user in @group.users %>
    <li><%= link_to user.email, user_path(user) %></li>
  <% end %> 
</ul>
<li><%= link_to "加入团队", groupships_path(:group_id => @group),
               :method => :post  %></li>

app/views/groups/edit.html.erb
<%= render 'form' %>

<p>
  <%= link_to "Show", @group %> |
  <%= link_to "View All", groups_path %>
</p>

app/views/groups/index.html.erb
<table id="groups" class="table table-border table-striped table-hover">
  <thead>
    <tr>
      <th>目的地</th>
      <th>队伍名称</th>
      <th>团队主页</th>
      <th>队伍主题</th>
    </tr>
    <thead>
      <tbody>
        <% for group in @groups %>
        <tr>
          <td><%= group.destination %></td>
          <td><%= group.name %></td>
          <td><%= link_to "团队主页",group_path(group)%></td>
          <td><%= group.description %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

app/views/groups/new.html.erb
<div id="team-form">
	<div class="modal-header">
		<h3>创建团队</h3>
	</div>
	<%= render 'form' %>
</div>
<p><%= link_to "Back to List", groups_path %></p>

app/views/groups/show.html.erb
<ul id="team_info">
  <li>队伍名称：<%= @group.name %></li>
  <li>队伍主题：<%= @group.description %></li>
  <li>目的地：<%= @group.destination %></li>
  <li>出发集结地：<%= @group.start %></li>
  <li>
    <%= render "team_members" %>  
  </li>  
</ul>
<div class="action">
  <%= link_to "删除团队", @group, :confirm => 'Are you sure?', :method => :delete %>
</div>

app/views/homes/index.html.erb
<%= render "share/slide" %>

app/views/layouts/_header.html.erb
  <div class="navbar navbar-fluid-top">
    <div class="">
      <div class="container-fluid">
        <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" id="logo" href=<%= homes_path %> >途趣网</a>
        <div class="container-fluid nav-collapse">
          <ul class="nav">
            <li><%= link_to t("nav.teams"), groups_path %></li>
            <div class="nav pull-right">
              <% if user_signed_in? %>
              <li><%= link_to "个人主页", user_path(current_user) %></li>
              <li><%= link_to "退出", destroy_user_session_path,
                              :method => :delete  %></li>
              <% else %>
              <li><%= link_to "登录", new_user_session_path%></li>
              <li><%= link_to "注册", new_user_registration_path%></li>
              <% end %>
            </div>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Team" %></title>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag "application", :media => "all" %>
</head>
<body>
  <header>
    <%= render 'layouts/header' %>
    <hr>
  </header>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span10 offset1">
        <%= flash[:notice] || nil %>
        <%= yield  %>
        <%= debug params %>
      </div>
    </div><!--/row-->
  </div> <!-- /container -->
</body>
</html>

app/views/share/_slide.html.erb
<div id="myCarousel" class="carousel">
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item"><%= image_tag @first_image_url %></div>
    <% for url in @image_urls %>
    	<div class="item"><%= image_tag url %></div>
    <% end %>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <p>
    <%= f.input :name %>
  </p>
  <p><%= f.button  :submit %></p>
<% end %>

app/views/users/_join_team_info.html.erb
 <ul>
 	<% if @user.groupships.length == 0 %>
 	<li>你还没有加入任何团队～～～</li>
 	<% else %>
 	<li>加入的团队</li>
 		<% for groupship in @user.groupships %>
 		<li>
 			<%= link_to groupship.group.name, groupship.group %>
 			<%= link_to "退出团队", groupship_path(groupship), 
 									confirm: "Are you sure", :method => :delete %>
 		</li>     
 		<% end %>
 	<% end %>
 </ul>

app/views/users/_link.html.erb
<p>
  <%= link_to "Edit", edit_user_path(@user),:remote => true %>
  <%= link_to "Create new Team",new_group_path ,:remote => true %>
</p>

app/views/users/show.html.erb
<%= form_for @user, :html => {:multipart => true} do |f| %>
<div class="row-fluid">
  <div class="span4" id="user_info">
    <div id="user_avatar">
      <%= image_tag(@user.avatar_url(:thumb).to_s) if @user.avatar? %>
      <%= f.file_field :avatar %>
      <%= f.submit '确认', class: "btn-primary"%>
    </div>
    <p>email: <%= @user.email %></p>
    <p>
      <label>qq: </label> 
      <%= best_in_place @user, :qq %>
    </p>
    <p><label>性别: </label><%= best_in_place @user, :gender %></p>
    <p><%= render 'join_team_info' %></p>
    <p>
    </p>
  </div>

  <div class="span8">
    <%= link_to "创建新团队", new_group_path %>
  </div>
</div>
<% end %>